services:
  - type: web
    name: nft-sell-os-bot
    runtime: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @workspace/api-server run build
    startCommand: pnpm --filter @workspace/api-server run start
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_CHAT_ID
        sync: false
      - key: KPAY_NUMBER
        value: "09771351671"
      - key: GROUP_CHAT_ID
        sync: false
      - key: MONGO_URI
        fromDatabase:
          name: pizza-db
          property: connectionString
      - key: MONGODB_URI
        fromDatabase:
          name: pizza-db
          property: connectionString

databases:
  - name: pizza-db
    plan: free
    region: singapore
